loadTimeData.data = {
    "about": "about",
    "addFunds": "add funds",
    "autoTipText": "You are automatically sending a tip to:",
    "bat": "BAT",
    "doMonthly": "Set monthly tip",
    "donationAmount": "Tip amount",
    "firstTipDateText": "Your first monthly tip will be sent on:",
    "fontfamily": "system-ui, sans-serif",
    "fontsize": "75%",
    "language": "en",
    "makeMonthly": "Make this monthly",
    "monthlyText": "Monthly",
    "notEnoughTokens": "Not enough tokens. Please",
    "on": "on",
    "rewardsBannerText1": "You can support this site by sending a tip. It’s a way of thanking them for making great content. Verified content creators get paid for their tips during the first week of each calendar month.",
    "rewardsBannerText2": "If you like, you can schedule monthly tips to support this site on a continuous basis.",
    "sendDonation": "Send my Tip",
    "siteBannerNoticeNote": "NOTE:",
    "siteBannerNoticeText": "This creator has not yet signed up to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.",
    "textdirection": "ltr",
    "thankYou": "Thank you",
    "tipText": "You've just sent a tip to:",
    "tokens": "tokens",
    "unVerifiedTextMore": "Learn more.",
    "walletBalance": "wallet balance",
    "welcome": "Welcome!"
};
